### PR TITLE
chore(gradle): Simpler Kotlin DSL Property Assignment

### PR DESCRIPTION
**Pull request by SimonMarquis**
Following #782

### CODE REVIEW

**Review by soulcramer — DISMISSED** [review]

**Review by kazaky — DISMISSED** [review]

**Comment by SimonMarquis** [comment]
@spark-ui-bot spotless

**Comment by SimonMarquis** [comment]
Let's wait for https://github.com/pinterest/ktlint/pull/2382

**Comment by SimonMarquis** [comment]
@soulcramer this PR is ready to be reviewed :)

**Review by soulcramer — APPROVED** [review]
Goot to me!

**Pull request merged**
