### PR TITLE
feat(paparazzi): Configure `useDeviceResolution` to `true`

### PR DESCRIPTION
**Pull request by SimonMarquis**

### CODE REVIEW

**Comment by SimonMarquis** [comment]
@spark-ui-bot paparazzi

**Comment by SimonMarquis** [comment]
@spark-ui-bot paparazzi

**Comment by SimonMarquis** [comment]
@spark-ui-bot paparazzi

**Review by kazaky — APPROVED** [review]

**Comment by SimonMarquis** [comment]
@spark-ui-bot paparazzi

**Comment by SimonMarquis** [comment]
@soulcramer can you make this change outside this PR?

**Comment by soulcramer** [comment]
> @soulcramer can you make this change outside this PR?

Done, I'll create a separate change on top of it

**Comment by soulcramer** [comment]
@spark-ui-bot paparazzi

**Comment by SimonMarquis** [comment]
@spark-ui-bot paparazzi

**Pull request merged**
