### PR TITLE
feat: screenshot tests for all `SparkIcon`s

### PR DESCRIPTION
**Pull request by SimonMarquis**
## 📋 Changes

This adds screenshot tests to all `SparkIcon`s to detect regressions.

- [x] Needs to be rebased on top of:
  - #841

### CODE REVIEW

**Comment by SimonMarquis** [comment]
@spark-ui-bot paparazzi

**Comment by SimonMarquis** [comment]
Needs to be rebased on top of:
- #841

**Comment by SimonMarquis** [comment]
@spark-ui-bot paparazzi

**Comment by SimonMarquis** [comment]
@spark-ui-bot paparazzi

**Review by soulcramer — APPROVED** [review]

**Pull request merged**
