### PR TITLE
fix: checkbox checkmark was using onPrimary instead of onColor from intent

### PR DESCRIPTION
**Pull request by soulcramer**
## 📋 Changes

Use intent on color for checkbox checkmark and use `Transparent` as surface color in configurators when the intent is not `surface`

## 🤔 Context

When testing the KA flavor of Polaris I noticed that the checkbox was using `onMain` for the checkmark which is the same color as basic in this theme and would make the checkbox fully basic.

## ✅ Checklist

- [x] I have reviewed the submitted code.
- [x] I have tested on a phone in the catalog app.

## 📸 Screenshots

image

image

### CODE REVIEW

**Review by SimonMarquis — APPROVED** [review]
LGTM 👍

**Comment by SimonMarquis** [comment]
@spark-ui-bot spotless

**Comment by SimonMarquis** [comment]
🙈 spotless command will be fixed in https://github.com/adevinta/spark-android/pull/768

**Review by kazaky — APPROVED** [review]
LGTM

**Comment by soulcramer** [comment]
@spark-ui-bot paparazzi golden images

**Pull request merged**
