### PR TITLE
feat(ci): add PR title format validator

### PR DESCRIPTION
**Pull request by SimonMarquis**
Closing #19

### CODE REVIEW

**Comment by SimonMarquis** [comment]
Here is an example where it fails: https://github.com/adevinta/spark-android/actions/runs/4136282759
And one where it succeeds: https://github.com/adevinta/spark-android/actions/runs/4136298751

@soulcramer WDYT? Is it enough for now?

**Review by soulcramer — COMMENTED** [review]
LGTM, thanks :D

**Review by soulcramer — COMMENTED** [review]
I selected **Comment** instead of **Approve** 🙄

**Review by soulcramer — APPROVED** [review]
è_é
I said I Approve this change

**Pull request merged**
